const keywords = [
"java",
"javascript",
"java tutorial",
"python tutorial",
"php classes",
"Learn php",
"Learn to code",
"Web Development",
"freeCodeCamp",
"Kent C. Dodds",
"Learn React js",
"React 16",
"React Router",
"React native course",
"Advanced nodejs",
"Node js",
"Node.js Tutorial for Beginners",
"Node JS Full Course",
"Node.JS in One Video",
"Node.js Crash Course",
"NodeJS vs PHP | Which is best for beginners",
"JavaScript Tutorial for Beginners",
"JavaScript tutorial for beginners in Hindi",
"Learn JavaScript - Full Course for Beginners",
"JavaScript Tutorial for Beginners - Full Course in 8 Hours [2020]",
"JavaScript Full Course | JavaScript Tutorial For Beginners | JavaScript Training | Edureka",
"Online Learning platforms",
"udemy courses",
"upgrad courses",
"Redux basics",
"React basics",
"Advanced react classes",
"Covid 19",
"Epidemic outbreak",
"Pandemic outbreak 2020",
"Italy 2020",
"India lockdown",
"Narendra Modi",
"Donal trump",
"Italy sues China",
"USA superpower",
"Facebook",
"Spotify", 
"productivity",
"home decor",
"travel bloggers",
"travel videos",
"beer brewing","computer science", "millionaire", "mindset training", "tech guruji", "techincal guru",
"sourabh sabharwal", "world in making", "world epidemic", "world hysteria", "world panic", "war 2020", 
"syria warzone",
"Learn python", "Python", "Pyhton full course"];

export default keywords;